// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: registry.proto

package apiv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceRegistry_ServiceReg_FullMethodName   = "/registry.v1.ServiceRegistry/ServiceReg"
	ServiceRegistry_ServiceDereg_FullMethodName = "/registry.v1.ServiceRegistry/ServiceDereg"
	ServiceRegistry_GetService_FullMethodName   = "/registry.v1.ServiceRegistry/GetService"
	ServiceRegistry_ListServices_FullMethodName = "/registry.v1.ServiceRegistry/ListServices"
)

// ServiceRegistryClient is the client API for ServiceRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceRegistryClient interface {
	ServiceReg(ctx context.Context, in *ServiceRegRequest, opts ...grpc.CallOption) (*ServiceRegResponse, error)
	ServiceDereg(ctx context.Context, in *ServiceDeregRequest, opts ...grpc.CallOption) (*ServiceDeregResponse, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
}

type serviceRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceRegistryClient(cc grpc.ClientConnInterface) ServiceRegistryClient {
	return &serviceRegistryClient{cc}
}

func (c *serviceRegistryClient) ServiceReg(ctx context.Context, in *ServiceRegRequest, opts ...grpc.CallOption) (*ServiceRegResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRegResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_ServiceReg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) ServiceDereg(ctx context.Context, in *ServiceDeregRequest, opts ...grpc.CallOption) (*ServiceDeregResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceDeregResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_ServiceDereg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceRegistryServer is the server API for ServiceRegistry service.
// All implementations must embed UnimplementedServiceRegistryServer
// for forward compatibility.
type ServiceRegistryServer interface {
	ServiceReg(context.Context, *ServiceRegRequest) (*ServiceRegResponse, error)
	ServiceDereg(context.Context, *ServiceDeregRequest) (*ServiceDeregResponse, error)
	GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	mustEmbedUnimplementedServiceRegistryServer()
}

// UnimplementedServiceRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceRegistryServer struct{}

func (UnimplementedServiceRegistryServer) ServiceReg(context.Context, *ServiceRegRequest) (*ServiceRegResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceReg not implemented")
}
func (UnimplementedServiceRegistryServer) ServiceDereg(context.Context, *ServiceDeregRequest) (*ServiceDeregResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceDereg not implemented")
}
func (UnimplementedServiceRegistryServer) GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedServiceRegistryServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedServiceRegistryServer) mustEmbedUnimplementedServiceRegistryServer() {}
func (UnimplementedServiceRegistryServer) testEmbeddedByValue()                         {}

// UnsafeServiceRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceRegistryServer will
// result in compilation errors.
type UnsafeServiceRegistryServer interface {
	mustEmbedUnimplementedServiceRegistryServer()
}

func RegisterServiceRegistryServer(s grpc.ServiceRegistrar, srv ServiceRegistryServer) {
	// If the following call pancis, it indicates UnimplementedServiceRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceRegistry_ServiceDesc, srv)
}

func _ServiceRegistry_ServiceReg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRegRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).ServiceReg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_ServiceReg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).ServiceReg(ctx, req.(*ServiceRegRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_ServiceDereg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceDeregRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).ServiceDereg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_ServiceDereg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).ServiceDereg(ctx, req.(*ServiceDeregRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceRegistry_ServiceDesc is the grpc.ServiceDesc for ServiceRegistry service.
// It's only intended for direct use with grpc.ServiceReg,
// and not to be introspected or modified (even as a copy)
var ServiceRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.v1.ServiceRegistry",
	HandlerType: (*ServiceRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServiceReg",
			Handler:    _ServiceRegistry_ServiceReg_Handler,
		},
		{
			MethodName: "ServiceDereg",
			Handler:    _ServiceRegistry_ServiceDereg_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _ServiceRegistry_GetService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ServiceRegistry_ListServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}

const (
	RegPeer_JoinNode_FullMethodName        = "/registry.v1.RegPeer/JoinNode"
	RegPeer_GossipUpd_FullMethodName       = "/registry.v1.RegPeer/GossipUpd"
	RegPeer_AntyEntropyPull_FullMethodName = "/registry.v1.RegPeer/AntyEntropyPull"
)

// RegPeerClient is the client API for RegPeer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegPeerClient interface {
	JoinNode(ctx context.Context, in *JoinNodeRequest, opts ...grpc.CallOption) (*JoinNodeResponse, error)
	GossipUpd(ctx context.Context, in *GossipUpdRequest, opts ...grpc.CallOption) (*GossipUpdResponse, error)
	AntyEntropyPull(ctx context.Context, in *AntyEntropyPullRequest, opts ...grpc.CallOption) (*AntyEntropyPullResponse, error)
}

type regPeerClient struct {
	cc grpc.ClientConnInterface
}

func NewRegPeerClient(cc grpc.ClientConnInterface) RegPeerClient {
	return &regPeerClient{cc}
}

func (c *regPeerClient) JoinNode(ctx context.Context, in *JoinNodeRequest, opts ...grpc.CallOption) (*JoinNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinNodeResponse)
	err := c.cc.Invoke(ctx, RegPeer_JoinNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regPeerClient) GossipUpd(ctx context.Context, in *GossipUpdRequest, opts ...grpc.CallOption) (*GossipUpdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipUpdResponse)
	err := c.cc.Invoke(ctx, RegPeer_GossipUpd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regPeerClient) AntyEntropyPull(ctx context.Context, in *AntyEntropyPullRequest, opts ...grpc.CallOption) (*AntyEntropyPullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AntyEntropyPullResponse)
	err := c.cc.Invoke(ctx, RegPeer_AntyEntropyPull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegPeerServer is the server API for RegPeer service.
// All implementations must embed UnimplementedRegPeerServer
// for forward compatibility.
type RegPeerServer interface {
	JoinNode(context.Context, *JoinNodeRequest) (*JoinNodeResponse, error)
	GossipUpd(context.Context, *GossipUpdRequest) (*GossipUpdResponse, error)
	AntyEntropyPull(context.Context, *AntyEntropyPullRequest) (*AntyEntropyPullResponse, error)
	mustEmbedUnimplementedRegPeerServer()
}

// UnimplementedRegPeerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegPeerServer struct{}

func (UnimplementedRegPeerServer) JoinNode(context.Context, *JoinNodeRequest) (*JoinNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinNode not implemented")
}
func (UnimplementedRegPeerServer) GossipUpd(context.Context, *GossipUpdRequest) (*GossipUpdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GossipUpd not implemented")
}
func (UnimplementedRegPeerServer) AntyEntropyPull(context.Context, *AntyEntropyPullRequest) (*AntyEntropyPullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AntyEntropyPull not implemented")
}
func (UnimplementedRegPeerServer) mustEmbedUnimplementedRegPeerServer() {}
func (UnimplementedRegPeerServer) testEmbeddedByValue()                 {}

// UnsafeRegPeerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegPeerServer will
// result in compilation errors.
type UnsafeRegPeerServer interface {
	mustEmbedUnimplementedRegPeerServer()
}

func RegisterRegPeerServer(s grpc.ServiceRegistrar, srv RegPeerServer) {
	// If the following call pancis, it indicates UnimplementedRegPeerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegPeer_ServiceDesc, srv)
}

func _RegPeer_JoinNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegPeerServer).JoinNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegPeer_JoinNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegPeerServer).JoinNode(ctx, req.(*JoinNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegPeer_GossipUpd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipUpdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegPeerServer).GossipUpd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegPeer_GossipUpd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegPeerServer).GossipUpd(ctx, req.(*GossipUpdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegPeer_AntyEntropyPull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AntyEntropyPullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegPeerServer).AntyEntropyPull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegPeer_AntyEntropyPull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegPeerServer).AntyEntropyPull(ctx, req.(*AntyEntropyPullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegPeer_ServiceDesc is the grpc.ServiceDesc for RegPeer service.
// It's only intended for direct use with grpc.ServiceReg,
// and not to be introspected or modified (even as a copy)
var RegPeer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.v1.RegPeer",
	HandlerType: (*RegPeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinNode",
			Handler:    _RegPeer_JoinNode_Handler,
		},
		{
			MethodName: "GossipUpd",
			Handler:    _RegPeer_GossipUpd_Handler,
		},
		{
			MethodName: "AntyEntropyPull",
			Handler:    _RegPeer_AntyEntropyPull_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
